-- Stage A follow-up — enforcement triggers, source backfill + NOT NULL,
-- on-delete-set-null on registrations.user_id.
--
-- Layered on top of 20260829090000_account_professional_profile.sql (which
-- shipped the columns/table/policies/base grants). This migration adds the
-- product-plan constraints that were deferred to Stage B in that file but
-- which are DB-level obligations, not application logic:
--
--   1. On-delete behaviour: registrations.user_id becomes ON DELETE SET NULL.
--      Product intent (plan §1.7 + §5.4): a user disappearing must not delete
--      their attendance record — the row demotes to guest, keeping the
--      attendance authoritative for audit / cycle-return reconstruction.
--
--   2. registrations.source becomes NOT NULL with a default. Legacy rows
--      predating this slice (registered_at < 2026-08-29) are backfilled to
--      'system_migration' so the analytics view of "how did this registration
--      arrive" stays honest — the previous nullable+no-backfill left legacy
--      rows silently indistinguishable from a real self_registration once
--      the app started writing that default.
--
--   3. Snapshot / user_id / source immutability from client, and the
--      guest-INSERT user_id block (plan §8.2 + §8.3). Without these the
--      existing registrations_organizer_update_own RLS UPDATE lets an
--      organiser overwrite profile_snapshot or reattach user_id at will.
--      The triggers key on current_user, letting service_role (Server
--      Actions in register/claim paths) and postgres (definer functions)
--      through while blocking direct authenticated writes.
--
--   4. professional_profiles.speaker_discovery_opt_in_at is kept in sync
--      with speaker_discovery_opt_in automatically. Cheaper as a trigger
--      than as a rule every writer has to remember.

-- ---------------------------------------------------------------------------
-- 1. on delete set null for registrations.user_id
-- ---------------------------------------------------------------------------

do $$
declare
  cn text;
begin
  -- Defensive: the FK name is auto-generated by Postgres so look it up
  -- rather than hardcoding, in case a future rename slips in.
  select tc.constraint_name into cn
  from information_schema.table_constraints tc
  join information_schema.key_column_usage kcu
    on tc.constraint_name = kcu.constraint_name
    and tc.table_schema  = kcu.table_schema
  where tc.table_schema = 'public'
    and tc.table_name   = 'registrations'
    and tc.constraint_type = 'FOREIGN KEY'
    and kcu.column_name = 'user_id';
  if cn is not null then
    execute format('alter table public.registrations drop constraint %I', cn);
  end if;
end $$;

alter table public.registrations
  add constraint registrations_user_id_fkey
  foreign key (user_id) references public.users(id) on delete set null;

-- ---------------------------------------------------------------------------
-- 2. source backfill + NOT NULL
-- ---------------------------------------------------------------------------

update public.registrations
  set source = 'system_migration'
  where source is null;

alter table public.registrations
  alter column source set default 'self_registration',
  alter column source set not null;

-- ---------------------------------------------------------------------------
-- 3. Client-immutability triggers on registrations
-- ---------------------------------------------------------------------------
--
-- current_user (not auth.role()) because SECURITY DEFINER functions called
-- by an authenticated user keep the JWT claim intact so auth.role() still
-- returns 'authenticated', but current_user reflects the actual DB role
-- (function owner = postgres). That is the only way to let definer paths
-- through while blocking direct RLS-scoped UPDATEs from the same session.

create or replace function public.registrations_link_columns_immutable_from_client()
returns trigger
language plpgsql
as $$
begin
  if TG_OP = 'UPDATE' and current_user in ('authenticated', 'anon') then
    if NEW.profile_snapshot is distinct from OLD.profile_snapshot then
      raise exception 'profile_snapshot is written only via register/claim definer or Server Action paths'
        using errcode = '42501';
    end if;
    if NEW.user_id is distinct from OLD.user_id then
      raise exception 'registrations.user_id is written only via register-while-logged-in or claim paths'
        using errcode = '42501';
    end if;
    if NEW.source is distinct from OLD.source then
      raise exception 'registrations.source is set at insert time only and is not client-mutable'
        using errcode = '42501';
    end if;
  end if;
  return NEW;
end;
$$;

create trigger registrations_link_columns_immutable_from_client_trg
  before update on public.registrations
  for each row execute function public.registrations_link_columns_immutable_from_client();

create or replace function public.registrations_guest_insert_no_user_id()
returns trigger
language plpgsql
as $$
begin
  if TG_OP = 'INSERT' and current_user in ('authenticated', 'anon') and NEW.user_id is not null then
    raise exception 'registrations.user_id may only be set via register-while-logged-in or claim paths (Server Action)'
      using errcode = '42501';
  end if;
  return NEW;
end;
$$;

create trigger registrations_guest_insert_no_user_id_trg
  before insert on public.registrations
  for each row execute function public.registrations_guest_insert_no_user_id();

-- ---------------------------------------------------------------------------
-- 4. professional_profiles: opt-in timestamp sync
-- ---------------------------------------------------------------------------

create or replace function public.professional_profiles_touch_discovery_opt_in_at()
returns trigger
language plpgsql
as $$
begin
  if TG_OP = 'INSERT' then
    if NEW.speaker_discovery_opt_in then
      NEW.speaker_discovery_opt_in_at := now();
    end if;
  elsif TG_OP = 'UPDATE' then
    if NEW.speaker_discovery_opt_in is distinct from OLD.speaker_discovery_opt_in then
      NEW.speaker_discovery_opt_in_at :=
        case when NEW.speaker_discovery_opt_in then now() else null end;
    end if;
  end if;
  return NEW;
end;
$$;

create trigger professional_profiles_discovery_opt_in_at_trg
  before insert or update on public.professional_profiles
  for each row execute function public.professional_profiles_touch_discovery_opt_in_at();

-- ---------------------------------------------------------------------------
-- Self-check: assert the four triggers exist and the source column is
-- NOT NULL with the expected default. Fails the migration loudly if the
-- shipped shape drifts from the plan intent.
-- ---------------------------------------------------------------------------
do $$
declare
  n int;
  is_null_ok text;
  col_default text;
begin
  select count(*) into n from information_schema.triggers
    where trigger_schema = 'public'
      and trigger_name in (
        'registrations_link_columns_immutable_from_client_trg',
        'registrations_guest_insert_no_user_id_trg',
        'professional_profiles_discovery_opt_in_at_trg'
      );
  -- Two triggers on registrations, one on professional_profiles = 3 rows in
  -- information_schema.triggers (one row per trigger); the UPDATE trigger
  -- shows once because it's UPDATE only.
  if n < 3 then
    raise exception 'stage-a enforcement self-check: expected 3 trigger rows, found %', n;
  end if;

  select is_nullable, column_default
    into is_null_ok, col_default
  from information_schema.columns
    where table_schema = 'public'
      and table_name   = 'registrations'
      and column_name  = 'source';
  if is_null_ok <> 'NO' then
    raise exception 'stage-a enforcement self-check: registrations.source is still nullable';
  end if;
  if col_default is null or col_default not like '%self_registration%' then
    raise exception 'stage-a enforcement self-check: registrations.source default is not self_registration';
  end if;

  raise notice 'stage-a enforcement self-check: all assertions passed';
end $$;
